public with sharing class lwc_Constant {
	
	// Error message constant (Should be in custom labels, but this is for readability)
	public static final String INPUT_ERROR_MESSAGE		=  'Unexpected method input';
	public static final String CALC_HIS_NO_R_MESSAGE	=  'Current user does not have read access to the lwc_Calculator_History__c object';
	public static final String CALC_HIS_NO_RC_MESSAGE	=  'Current user does not have read and create access to the lwc_Calculator_History__c object';
}
